In [2]:
import numpy as np

def get_x(K, N):
    x=[]
    for i in range(K+1):
        for j in range(N+1):
            for s in range(3):
                if((i!=0 or s!=0) and (i!=0 or j!=0 or s!=2) and (j!=0 or s!=1)):
                    x.append((i,j,s))
    return x

def get_c(x, K, gamma, nu):
    len_x = len(x)
    c=np.zeros(len_x)
    for i in range(len_x):
        if x[i][0] == 0: c[i] = gamma
        if (x[i][0] == K and x[i][2] == 1): c[i] = nu
    return c

def get_p(x, K, N, mu, nu, lam):
    len_x = len(x)
    p=np.zeros((2,len_x, len_x))
    for i in range(len_x):
        for j in range(len_x):
            if x[i][2] == 0:
                for a in range(2):
                    if (x[j][0] == (x[i][0]-1)) and (x[j][1] == min(x[i][1]+a,N)) and (x[j][2]==0) and (x[i][0]>1):
                        p[a][i][j]=mu/nu
                    if (x[j][0]==(x[i][0]-1)) and (x[j][1]==min(x[i][1]+a,N)) and (x[j][2]==1):
                        p[a][i][j]=lam*x[i][1]/nu
                    if (x[j][0]==(x[i][0]-1)) and (x[j][1]==min(x[i][1]+a,N)) and (x[j][2]==2):
                        if (x[i][0]>1):
                            p[a][i][j]=1-(mu+lam*x[i][1])/nu
                        else:
                            p[a][i][j]=1-lam*x[i][1]/nu
            if x[i][2]==1:
                for a in range(2):            
                    if (x[j][0]==min(x[i][0]+1,K)) and (x[j][1]==x[i][1]+a-1) and (x[j][2]==0):
                         p[a][i][j]=mu/nu
                    if (x[j][0]==min(x[i][0]+1,K)) and (x[j][1]==x[i][1]+a-1) and (x[j][2]==1):
                         p[a][i][j]=lam*(x[i][1]+a-1)/nu
                    if (x[j][0]==min(x[i][0]+1,K)) and (x[j][1]==x[i][1]+a-1) and (x[j][2]==2): 
                         p[a][i][j]=1-(mu+lam*(x[i][1]+a-1))/nu
            if x[i][2]==2:
                if (x[j][0]==x[i][0]) and (x[j][1]==x[i][1]) and (x[j][2]==0) and (x[i][0]>0):
                     p[0][i][j]=mu/nu
                if (x[j][0]==x[i][0]) and (x[j][1]==x[i][1]) and (x[j][2]==1): 
                     p[0][i][j]=lam*x[i][1]/nu
                if (x[j][0]==x[i][0]) and (x[j][1]==x[i][1]) and (x[j][2]==2): 
                    if (x[i][0]>0): 
                        p[0][i][j]=1-(mu+lam*x[i][1])/nu 
                    else:
                        p[0][i][j]=1-lam*x[i][1]/nu
    return p

def get_theta_pi(x, p, c):
    len_x = len(x)
    eps = 10 ** -5
    tau = 0.99999
    k = 0
    h=np.zeros(len_x)
    e=1.0
    while e > eps:
        T=np.zeros(len_x)
        h1=np.zeros(len_x)
        pi=np.zeros(len_x)
        for i in range(len_x):
            if (x[i][2]==2):
                min_a = sum(p[0][i][j]*h[j] for j in range(len_x))
                imin_a = 0
            elif (x[i][0]==1) and (x[i][1]==0) and (x[i][2]==0):
                min_a=sum(p[1][i][j] * h[j] for j in range(len_x)) 
                imin_a=1
            else:
                summ_1 = sum(p[0][i][j] * h[j] for j in range(len_x))
                summ_2 = sum(p[1][i][j] * h[j] for j in range(len_x))
                min_a = min([summ_1, summ_2])
                if summ_1 > summ_2:
                    imin_a = 1
                else:
                    imin_a = 0
            T[i]=c[i]+min_a
            h1[i]=(1-tau)*h[i]+tau*(T[i]-T[0])
            pi[i]=imin_a
        e=max(abs(h1-h))
        h=h1
        k=k+1
    theta=tau*T[0]
    return theta, pi

def make_calc(K, N, lam, mu, gamma):
    nu=N*lam+mu
    x = get_x(K, N)
    len_x = len(x)
    c = get_c(x, K, gamma, nu)
    p = get_p(x, K, N, mu, nu, lam)
    theta = get_theta_pi(x, p, c)[0]
    pi = get_theta_pi(x, p, c)[1]
    return x, theta, pi

# #вывод таблицы      
# print("\ns = 0:\n")  
# print_arr = np.empty(K+1)
# for r in range(N, -1, -1):
#     for q in range(K+1):
#         if (q, r, 0) in x:
#             print_arr[q] = pi[x.index((q, r, 0))]
#     print(print_arr)
# print("\ns = 1:\n")
# print_arr = np.empty(K+1)
# for r in range(N, 0, -1):
#     for q in range(K+1):
#         if (q, r, 1) in x:
#             print_arr[q] = pi[x.index((q, r, 1))]
#     print(print_arr)

282
0.21702335596005332

s = 0:

[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 0.]
[1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 0.]
[1. 1. 1. 1. 0. 0.]
[1. 1. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]

s = 1:

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 0.]
[1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 0.]
[1. 1. 1. 1. 0. 0.]
[1. 1. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
